In [1]:
import pandas as pd

# Data for the DataFrame
data = {
    "Technology": [
        "Python, Django, MySQL",
        "Machine Learning, Python, TensorFlow",
        "Large Language Models, Python, PyTorch",
        "Deep Learning, Keras, Python",
        "Flutter, Firebase, GraphQL",
        "React Native, Node.js, MongoDB",
        "iOS, Swift, Core Data",
        "Android, Java, Room Persistence",
        "Kotlin, Android, Firebase",
        "Web Development, React, Node.js",
        "Frontend, TypeScript, Angular",
        "Backend, Kotlin, Spring Boot",
        "Full-stack, JavaScript, Express.js",
        "Cloud Computing, AWS, Python",
        "AI, Python, scikit-learn",
        "Data Engineering, Apache Spark, Python",
        "Mobile Development, Flutter, Dart",
        "Web App Development, Vue.js, Ruby on Rails",
        "Game Development, Unity, C#",
        "DevOps, Jenkins, Docker"
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
df

                                    Technology
0                        Python, Django, MySQL
1         Machine Learning, Python, TensorFlow
2       Large Language Models, Python, PyTorch
3                 Deep Learning, Keras, Python
4                   Flutter, Firebase, GraphQL
5               React Native, Node.js, MongoDB
6                        iOS, Swift, Core Data
7              Android, Java, Room Persistence
8                    Kotlin, Android, Firebase
9              Web Development, React, Node.js
10               Frontend, TypeScript, Angular
11                Backend, Kotlin, Spring Boot
12          Full-stack, JavaScript, Express.js
13                Cloud Computing, AWS, Python
14                    AI, Python, scikit-learn
15      Data Engineering, Apache Spark, Python
16           Mobile Development, Flutter, Dart
17  Web App Development, Vue.js, Ruby on Rails
18                 Game Development, Unity, C#
19                     DevOps, Jenkins, Docker

In [2]:
file_path = r"C:\Users\vikas\OneDrive\Desktop\Next-Gen-Interview-Prep-AI-Generated-Questions-Based-on-Your-Resume\portfolio.csv"
df.to_csv(file_path, index=False)

In [3]:
print("The End")

The End